// COLLEGE TRIP
    $(document).ready(function () {
      $('#CLG').lightSlider({
        item: 3,
        loop: false,
        slideMove: 2,
        easing: 'cubic-bezier(0.25, 0, 0.25, 1)',
        speed: 900,
        responsive: [
          {
            breakpoint: 800,
            settings: {
              item: 2,
              slideMove: 1,
              slideMargin: 3,
            }
          },
          {
            breakpoint: 480,
            settings: {
              item: 1,
              slideMove: 1
            }
          }
        ]
      });
    });

// ------------------------------------------------------------------------------
    
    $(document).ready(function () {
      $('#responsive').lightSlider({
        item: 3,
        loop: false,
        slideMove: 2,
        easing: 'cubic-bezier(0.25, 0, 0.25, 1)',
        speed: 800,
        responsive: [
          {
            breakpoint: 800,
            settings: {
              item: 2,
              slideMove: 1,
              slideMargin: 3,
            }
          },
          {
            breakpoint: 480,
            settings: {
              item: 1,
              slideMove: 1
            }
          }
        ]
      });
    });
  
// ------------------------------------------------------------------------------------------
  
    $(document).ready(function () {
      $('#jkl').lightSlider({
        item: 3,
        loop: false,
        slideMove: 2,
        easing: 'cubic-bezier(0.25, 0, 0.25, 1)',
        speed: 900,
        responsive: [
          {
            breakpoint: 800,
            settings: {
              item: 2,
              slideMove: 1,
              slideMargin: 3,
            }
          },
          {
            breakpoint: 480,
            settings: {
              item: 1,
              slideMove: 1
            }
          }
        ]
      });
    });


// --------------------------------------------------------------------------------
    $(document).ready(function () {
      $('#ck').lightSlider({
        item: 3,
        loop: false,
        slideMove: 2,
        easing: 'cubic-bezier(0.25, 0, 0.25, 1)',
        speed: 900,
        responsive: [
          {
            breakpoint: 800,
            settings: {
              item: 2,
              slideMove: 1,
              slideMargin: 3,
            }
          },
          {
            breakpoint: 480,
            settings: {
              item: 1,
              slideMove: 1
            }
          }
        ]
      });
    });
//   ---------------------------------------------------------
$(document).ready(function () {
    $('#HON').lightSlider({
      item: 3,
      loop: false,
      slideMove: 2,
      easing: 'cubic-bezier(0.25, 0, 0.25, 1)',
      speed: 900,
      responsive: [
        {
          breakpoint: 800,
          settings: {
            item: 2,
            slideMove: 1,
            slideMargin: 3,
          }
        },
        {
          breakpoint: 480,
          settings: {
            item: 1,
            slideMove: 1
          }
        }
      ]
    });
  });

//   ----------------------------------------------------------------
$(document).ready(function () {
    $('#COR').lightSlider({
      item: 3,
      loop: false,
      slideMove: 2,
      easing: 'cubic-bezier(0.25, 0, 0.25, 1)',
      speed: 900,
      slideMargin: 3,
      responsive: [
        {
          breakpoint: 800,
          settings: {
            item: 2,
            slideMove: 1,
            slideMargin: 3,
          }
        },
        {
          breakpoint: 480,
          settings: {
            item: 1,
            slideMove: 1,
            slideMargin: 1
          }
        }
      ]
    });
  });
